name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write
  id-token: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Gradlew executable
      run: chmod +x ./gradlew
    - name: Making the jar
      run: ./gradlew jar

    - name: Unloading it
      uses: actions/upload-artifact@v4
      with:
          name: ${{ github.event.repository.name }}
          path: build/libs/

    - name: Create Release on GitHub
      id: create_release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: "v${{ github.run_number }}"
        name: "${{ github.event.repository.name }} ${{ github.run_number }}"
        body: "Automated release of version v${{ github.run_number }}."
        draft: false
        prerelease: false
        files: build/libs/*.jar
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
